#!/usr/bin/env python3
"""
Emit the canonical decay table for the research worker. §24.

    python3 tools/emit_decay.py            write research-worker/src/decay.generated.js
    python3 tools/emit_decay.py --check    fail if the file is out of sync

caney/research/decay.py owns the numbers; claims.js imports the module this writes. Same
arrangement as out/plan/parity.json: Python is the single source and the consumer reads
what Python emitted, because a calibrated value that lives in two places gets edited in
one. test_research.py runs --check.

It emits a JS MODULE rather than JSON on purpose. JSON imports need an assertion whose
syntax differs by runtime — `assert { type: "json" }` on Node 18, `with { type: "json" }`
on Node 22, neither under esbuild — so a .json file that bundles cleanly for the Worker
fails in the test runner. A module has no such problem anywhere.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from caney.research.decay import ALIASES, DECAY, DEFAULT   # noqa: E402

OUT = os.path.join(ROOT, "research-worker", "src", "decay.generated.js")

#: JS spells these in camelCase; the table is canonical in Python's snake_case.
_JS = {"ttl_seconds": "ttlSeconds", "half_life_days": "halfLifeDays", "floor": "floor"}


def payload():
    return {
        "decay": {k: {_JS[a]: b for a, b in v.items()} for k, v in DECAY.items()},
        "default": {_JS[a]: b for a, b in DEFAULT.items()},
        "aliases": dict(ALIASES),
    }


def module_source():
    p = payload()
    return (
        "// GENERATED by tools/emit_decay.py from caney/research/decay.py — do not edit.\n"
        "//\n"
        "// Python owns these numbers. The two halves of the research system used to carry\n"
        "// separate tables and disagreed by 18x on a month-old fishing report; a test\n"
        "// (`emit_decay.py --check`) now fails if this file drifts from the Python one.\n"
        "export const DECAY = %s;\n"
        "export const DEFAULT_DECAY = %s;\n"
        "export const DECAY_ALIASES = %s;\n"
        % (json.dumps(p["decay"], indent=2, sort_keys=True),
           json.dumps(p["default"], indent=2, sort_keys=True),
           json.dumps(p["aliases"], indent=2, sort_keys=True)))


def main():
    want = module_source()
    if "--check" in sys.argv:
        try:
            with open(OUT, encoding="utf-8") as fh:
                got = fh.read()
        except OSError:
            print("missing %s — run tools/emit_decay.py" % OUT)
            return 1
        if got != want:
            print("%s is out of sync with caney/research/decay.py — "
                  "run tools/emit_decay.py" % OUT)
            return 1
        print("decay.generated.js is in sync")
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(want)
    print("wrote %s (%d claim types)" % (OUT, len(DECAY)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
