"""
Fetching, inside a Worker. §30, §31, §32.

A Cloudflare Python Worker is Pyodide. `urllib.request.urlopen` does not work there and
cannot be made to — there are no sockets, only the platform's async `fetch`. The planner
must therefore never make a blocking call, and the source layer was rebuilt in
`caney/sources/runtime.py` so that it does not.

THE TWO-PASS TRICK is what makes that practical. A Worker cannot discover what to prefetch
by starting to plan, because the first missing source would already be an error. The
obvious fix — a manifest of URLs generated at build time and shipped in the bundle — does
not survive contact with CWMS, whose URLs carry `begin` and `end` timestamps computed from
the current hour. A baked manifest is wrong within the hour and silently returns yesterday.

So:

    PASS 1  Run the real snapshot builder against an EMPTY WorkerSourceRuntime, wrapped in
            a recorder. Every source asks for its URL, gets "not prefetched", and the
            snapshots come out degraded — which we throw away. What we keep is the exact
            set of URLs this instant needs, generated by the same code that will consume
            them, so it cannot drift.

    FETCH   All of them concurrently through the platform's fetch.

    PASS 2  Run the builder again over the populated runtime. No misses, no blocking.

The cost is building snapshots twice. That is pure arithmetic over in-memory dicts and
measured in single-digit milliseconds; the network round it replaces is measured in
hundreds. §32's filtering falls out of pass 1 for free: a striped-bass request only ever
touches the rivers its candidate zones sit on, so only those URLs are ever recorded.
"""
import asyncio
import json

from caney.sources import runtime as rt


async def _fetch_one(req, fetch, headers_cls, request_cls, timeout_ms=8000):
    """One upstream call. Returns (key, data, error) and never raises."""
    try:
        hdrs = {"User-Agent": "caney-api/3.0 (+https://caney.pages.dev)"}
        hdrs.update(req.headers or {})
        from js import Object
        from pyodide.ffi import to_js
        opts = to_js({"method": "GET", "headers": hdrs},
                     dict_converter=Object.fromEntries)
        resp = await fetch(req.url, opts)
        if not resp.ok:
            return req.key, None, "HTTP %s from %s" % (resp.status, _host(req.url))
        text = await resp.text()
        return req.key, json.loads(text), None
    except Exception as e:                          # noqa: BLE001 — failure is a value
        return req.key, None, "%s: %s" % (type(e).__name__, e)


def _host(url):
    try:
        return url.split("/")[2]
    except IndexError:
        return url[:40]


async def prefetch(build_fn, fetch, max_concurrency=12):
    """(WorkerSourceRuntime, stats). Runs pass 1, fetches, returns the filled runtime.

    `build_fn()` is the snapshot build — called once here to discover, and again by the
    caller against the returned runtime.
    """
    empty = rt.WorkerSourceRuntime()
    recorder = rt.RecordingSourceRuntime(empty)
    with rt.using(recorder):
        try:
            build_fn()
        except Exception:                           # noqa: BLE001
            # Pass 1's OUTPUT is discarded, so a failure in it is not fatal — what
            # matters is the request set recorded before it fell over. A source layer
            # that throws with every value missing is a plausible thing; refusing to
            # plan because the throwaway pass threw would be absurd.
            pass

    reqs = list(recorder.requests.values())
    filled = rt.WorkerSourceRuntime()
    stats = {"requested": len(reqs), "ok": 0, "failed": 0,
             "groups": len(recorder.groups)}
    if not reqs:
        return filled, stats

    sem = asyncio.Semaphore(max_concurrency)

    async def guarded(r):
        async with sem:
            return await _fetch_one(r, fetch, None, None)

    results = await asyncio.gather(*[guarded(r) for r in reqs],
                                   return_exceptions=True)
    for res in results:
        if isinstance(res, BaseException):
            stats["failed"] += 1
            continue
        key, data, err = res
        if err:
            filled.put(key, error=err)
            stats["failed"] += 1
        else:
            filled.put(key, data=data)
            stats["ok"] += 1
    return filled, stats
