"""
Fetching, inside a Worker. §30, §31, §32.

A Cloudflare Python Worker is Pyodide. `urllib.request.urlopen` does not work there and
cannot be made to — there are no sockets, only the platform's async `fetch`. The planner
must therefore never make a blocking call, and the source layer was rebuilt in
`caney/sources/runtime.py` so that it does not.

THE TWO-PASS TRICK is what makes that practical. A Worker cannot discover what to prefetch
by starting to plan, because the first missing source would already be an error. The
obvious fix — a manifest of URLs generated at build time and shipped in the bundle — does
not survive contact with CWMS, whose URLs carry `begin` and `end` timestamps computed from
the current hour. A baked manifest is wrong within the hour and silently returns yesterday.

So:

    PASS 1  Run the real snapshot builder against an EMPTY WorkerSourceRuntime, wrapped in
            a recorder. Every source asks for its URL, gets "not prefetched", and the
            snapshots come out degraded — which we throw away. What we keep is the exact
            set of URLs this instant needs, generated by the same code that will consume
            them, so it cannot drift.

    FETCH   All of them concurrently — through JS promises, NOT asyncio. Pyodide's
            WebLoop cannot run concurrent Python tasks at all; see the note in `prefetch`.

    PASS 2  Run the builder again over the populated runtime. No misses, no blocking.

The cost is building snapshots twice. That is pure arithmetic over in-memory dicts and
measured in single-digit milliseconds; the network round it replaces is measured in
hundreds. §32's filtering falls out of pass 1 for free: a striped-bass request only ever
touches the rivers its candidate zones sit on, so only those URLs are ever recorded.
"""
import json

from caney.sources import runtime as rt


def _opts(req):
    """JS fetch options for one request."""
    from js import Object
    from pyodide.ffi import to_js
    hdrs = {"User-Agent": "caney-api/3.0 (+https://caney.pages.dev)"}
    hdrs.update(req.headers or {})
    return to_js({"method": "GET", "headers": hdrs},
                 dict_converter=Object.fromEntries)


def _host(url):
    try:
        return url.split("/")[2]
    except IndexError:
        return url[:40]


async def prefetch(build_fn, fetch):
    """(WorkerSourceRuntime, stats). Runs pass 1, fetches, returns the filled runtime.

    `build_fn()` is the snapshot build — called once here to discover, and again by the
    caller against the returned runtime.
    """
    empty = rt.WorkerSourceRuntime()
    recorder = rt.RecordingSourceRuntime(empty)
    with rt.using(recorder):
        try:
            build_fn()
        except Exception:                           # noqa: BLE001
            # Pass 1's OUTPUT is discarded, so a failure in it is not fatal — what
            # matters is the request set recorded before it fell over. A source layer
            # that throws with every value missing is a plausible thing; refusing to
            # plan because the throwaway pass threw would be absurd.
            pass

    reqs = list(recorder.requests.values())
    filled = rt.WorkerSourceRuntime()
    stats = {"requested": len(reqs), "ok": 0, "failed": 0,
             "groups": len(recorder.groups)}
    if not reqs:
        return filled, stats

    stats["by_host"] = {}
    stats["errors"] = []
    # CONCURRENCY HAPPENS IN JS, NOT IN PYTHON'S EVENT LOOP.
    #
    # This used to be `asyncio.gather` over N coroutines behind a Semaphore, and it was the
    # root cause of nearly every mystery in this deployment. Pyodide's WebLoop cannot run
    # concurrent tasks; `wrangler tail` shows it plainly:
    #
    #   RuntimeError: Cannot enter into task <PyodideTask ...> while another task
    #   <PyodideTask ...> is being executed.
    #
    # That one error accounts for the source failures, the 1101 "worker threw" and the 1102
    # "resource limits" responses, because an invocation that raises out of a callback is
    # charged and discarded. It was invisible from outside: the exceptions land in the
    # worker's own log, and the planner's degraded-but-valid output looked like an upstream
    # problem.
    #
    # The fix is to let JavaScript own the parallelism. `fetch()` returns a JS promise
    # without Python awaiting it, so N of them are started and then awaited as ONE
    # `Promise.all` — one Python task, N concurrent requests. Two rounds are needed because
    # reading the body is a second promise; both are still a single await each.
    from js import Promise
    from pyodide.ffi import to_js

    async def _all(promises):
        """Await many JS promises as one Python task. [] is not a valid Promise.all input
        in every runtime, so it is short-circuited."""
        if not promises:
            return []
        res = await Promise.all(to_js(promises))
        return list(res)

    # BATCHED, because the platform caps SIMULTANEOUS OPEN CONNECTIONS at a handful —
    # separately from the 50-subrequest total. Removing the old Semaphore along with
    # asyncio took the throttle off too, and starting thirty fetches at once produced
    # exactly twelve successes per shard and eighteen failures: a connection cap, not a
    # concurrency bug. JS parallelism still does the work; it just does it six at a time.
    BATCH = 6

    responses, order = [], []
    for i in range(0, len(reqs), BATCH):
        chunk = reqs[i:i + BATCH]
        started, kept = [], []
        for r in chunk:
            try:
                started.append(fetch(r.url, _opts(r)))
                kept.append(r)
            except Exception as e:                  # noqa: BLE001
                filled.put(r.key, error="%s: %s" % (type(e).__name__, e))
                stats["failed"] += 1
                _tally(stats, r, False)
        # Promise.all REJECTS on the first failure, which would lose every other response
        # in the batch. A JS-level catch resolves to None instead, read back as a failure.
        guarded = []
        for pr in started:
            try:
                guarded.append(pr.catch(lambda _e: None))
            except Exception:                       # noqa: BLE001
                guarded.append(pr)
        responses.extend(await _all(guarded))
        order.extend(kept)

    # Reading the bodies is a second round of promises, batched for the same reason.
    pending = []
    for r, resp in zip(order, responses):
        if resp is None:
            filled.put(r.key, error="fetch failed for %s" % _host(r.url))
            stats["failed"] += 1
            _tally(stats, r, False)
            continue
        if not getattr(resp, "ok", False):
            filled.put(r.key, error="HTTP %s from %s" % (resp.status, _host(r.url)))
            stats["failed"] += 1
            _tally(stats, r, False)
            continue
        pending.append((r, resp))

    for i in range(0, len(pending), BATCH):
        chunk = pending[i:i + BATCH]
        promises, kept = [], []
        for r, resp in chunk:
            try:
                promises.append(resp.text().catch(lambda _e: None))
                kept.append(r)
            except Exception:                       # noqa: BLE001
                filled.put(r.key, error="could not read the body from %s" % _host(r.url))
                stats["failed"] += 1
                _tally(stats, r, False)
        bodies = await _all(promises)
        for r, raw in zip(kept, bodies):
            if raw is None:
                filled.put(r.key, error="empty body from %s" % _host(r.url))
                stats["failed"] += 1
                _tally(stats, r, False)
                continue
            try:
                filled.put(r.key, data=json.loads(str(raw)))
                stats["ok"] += 1
                _tally(stats, r, True)
            except ValueError as e:
                filled.put(r.key, error="not JSON from %s: %s" % (_host(r.url), e))
                stats["failed"] += 1
                _tally(stats, r, False)
    stats["batch_size"] = BATCH
    return filled, stats


def _tally(stats, req, ok):
    row = stats.setdefault("by_host", {}).setdefault(_host(req.url),
                                                    {"ok": 0, "failed": 0})
    row["ok" if ok else "failed"] += 1
    if not ok and len(stats.setdefault("errors", [])) < 12:
        stats["errors"].append({"key": req.key[:60], "host": _host(req.url)})



